### PR TITLE
Merge pull request #28 from povilux/development

### PR DESCRIPTION
**Pull request by aurimasko**
Galbūt galėtum tiesiog peržiūrėti kodą ir parekomenduoti, ką reiktų keisti? Ačiū

### CODE REVIEW

**Comment by tomasmuzas** [comment]
Bet čia nėr pakeitimų?

**Comment by aurimasko** [comment]
Joo, nėra.
Turiu omeny, kad užmesti akį apskritai į bent jau dalį kodo master branche, peržvelgti.. 
Nebent nerodo. Nes kaip suprantu nėra viskas ten labai gerai, bet iš kitos pusės nėra labai aišku, kas blogai.

**Comment by tomasmuzas** [comment]
Bet tai ten 700 failų...

**Comment by aurimasko** [comment]
na didžioji dalis ten nuotraukos.
kodo yra gal 10 failų max.

Pvz ką galima pasižiūrėti tai AddPersonView, AddPersonPresenter, PersonModel, DataManagement klases. Galbūt yra kažkas negero ten.

**Comment by kimutisd** [comment]
@aurimasko @maddddd @povilux 
General comments:
    in general solution looks a bit scattered - there are bunch of files inside folders, but there are bunch of them 
    under project standalone, and there are bunch of them that are not included, but not deleted as well. Its difficult to 
    find what is actually used. My advice would be to create two more projects under same solution (or as a separate, as a service),
    one of them could be dealing with video recognition, another with your specific business rules - how to know that a person is 
    missing;
    there are a lot of check in files that should not, like bin and obj
    there is a basic lack of exception handling
    private class variable MUST be named _nameOfVariable. Otherwise, it is very difficult to read code
    0 tests
Person.cs
    Why does person need CoordX and CoordY?
    Why there are a lot of optional parameters?
    Optional - general naming convention suggests Id over ID
User.cs
    ID = ++Count - what is that? isnt count reset each time program starts?
DataManagement.cs
    Why does FindUserByName,FindUserByEmail return object, and then later on does casting?
Folder logic
    Two things - there are no logic there and either way, it should not be called logic. Closest pitch would be BusinessLogic layer,
    in applications it is ussually as BL
ModelsFolder
    If you are placing files under Models folder, there is no point to name classes PersonModel, UserModel (it would be different if it would be ViewModel)
    UserModel looks redudant
Presenters folder
    comments should be in english, despite that you're all LT.
LoginPresenter.cs
    General tip - dont say that the password is incorrect, if you dont have blocking after X attempts - that is vulnerability
ImageHandler.cs
    commented out code is not welcome in the master(or develop)
Forms in general
    should be responsible for getting information from Form, and returning information back to the Form.
    One example: VideoPlayerForm knows how to play video, and that is a breach of SOLID.
    All forms should be revisited, to think what could be extracted.

**Pull request merged**
